Dean project1 1
chenpionaar1998/CodeU_Spring_2018 pull request #4
Opened 2018-03-09 03:39 UTC by chenpionaar1998

Project1 part 1

2018-03-09 07:43 UTC, nmccrack commented
I can't see anything to improve myself, it looks like it correctly does what the instructions for step 1 say to do.

2018-03-12 21:13 UTC, turtlefarmer requested changes

2018-03-12 21:13 UTC, turtlefarmer commented on src/main/java/codeu/controller/LoginServlet.java
> +      // TODO:add apssword
- Spelling
- Recommend adding TODOs in the format of "TODO(cheopionaar19983): Thing".  It'll make it easier to search for just your TODOs in the code later.

2018-03-12 21:13 UTC, turtlefarmer commented on src/main/java/codeu/model/store/basic/DefaultDataStore.java
> +      User user = new User(UUID.randomUUID(), randomUsernames.get(i), "password", Instant.now());
Consider either:

1)  Generating random password.  This would make it harder to log into these default users of course.
2)  If you think a static password is the right think, set the password as a class constant similar to the values like DEFAULT_USER_COUNT above.

2018-03-12 21:13 UTC, turtlefarmer commented on src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
>      persistentDataStore.writeThrough(inputUserOne);
You can still add a test for the password without the storage layer.  Verify that the password of the loaded users is null.

This validates the intent of the current state of your code.  It also provides a nice place holder for actual loading password verification for the next step.

2018-03-13 09:26 UTC, turtlefarmer approved these changes

2018-03-13 09:28 UTC, turtlefarmer commented
Thanks for the fixes.  The one comment in PersistentDataStoreTest would be nice to have, but it should be fixed by work in Project 1 part 2 anyways.  Feel free to merge without fixing.

2018-03-13 09:35 UTC, turtlefarmer approved these changes

2018-03-13 09:36 UTC, merged