Naomi development
chenpionaar1998/CodeU_Spring_2018 pull request #5
Opened 2018-03-13 23:12 UTC by nmccrack

Did step 2 of Project 1: added password logic to PersistenceDataStore methods for loading and writing users under the TODO comments.

Also fixed where about.jsp had about sections at top and bottom of page due to automatic merge conflict resolution, now looks like 
<img width="1048" alt="screen shot 2018-03-13 at 4 11 38 pm" src="https://user-images.githubusercontent.com/16550340/37374632-4502c806-26d9-11e8-96aa-5e17777743f4.png">
<img width="921" alt="screen shot 2018-03-13 at 4 11 29 pm" src="https://user-images.githubusercontent.com/16550340/37374633-46550bec-26d9-11e8-93d7-37d7c2a0e29e.png">

2018-03-14 05:17 UTC, turtlefarmer requested changes

2018-03-14 05:17 UTC, turtlefarmer commented on src/main/webapp/about.jsp
> -        <li><strong>Heng Sun (PA)</strong> Our supereme and righteous leader(PA).
I got clobbered :(

2018-03-14 05:17 UTC, turtlefarmer commented on src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
> +    String passwordTwo = "password2;";
Not that it's incorrect, but I feel the ';' inside the string is unintentional?

2018-03-15 06:10 UTC, chenpionaar1998 commented
Other than the ";" looks a bit odd, everything is looking good :)

2018-03-25 06:55 UTC, merged